Repository felix91gr/awesome-system-swift, pull requests merged in 2018-05, with the labels that each got.

#17 Use HTML <details> to make the "why testing" explanation collapsable
  README.md
Labels: polish - structure

#16 Extended the index, added tags and refined classification
  README.md
Labels: polish - structure, project request

#19 Adding TraceLog, GeoFeatures, and StickyLocking.
  README.md
Labels: project request

#23 Added Yams
  README.md
Labels: project request

#25 Updated "Why Testing" using html <summary> tag
  README.md
Labels: polish - structure

#24 Added RxSwift
  README.md
Labels: project request

#27 Move TraceLog's category and rename it
  README.md
Labels: polish - structure

#28 Removed some redundant assertions about the libs
  README.md
Labels: polish - wording
